### ISSUE TITLE
Little issue on startup with the new 1.17 of Spigot

### ISSUE THREAD

**Issue by CloudeLecaw** [KarmaConfigs/PlayerBTH#2]
```
[08:35:44] [Server thread/INFO]: [PlayerBTH] Enabling PlayerBTH v2.2.4
[08:35:44] [Server thread/INFO]: Injecting dependency JodaTimeV21010.jar into plugin 2.2.4
[08:35:44] [Server thread/WARN]: java.lang.ClassNotFoundException: ml.karmaconfigs.playerbth.shaded.karmapi.velocity.Logger
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.shaded.karmapi.common.utils.ReflectionUtil.scheduleLog(ReflectionUtil.java:230)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.shaded.karmapi.common.JarInjector.inject(JarInjector.java:204)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.Main.onEnable(Main.java:35)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[08:35:44] [Server thread/WARN]: java.lang.ClassNotFoundException: ml.karmaconfigs.playerbth.shaded.karmapi.velocity.Logger
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.shaded.karmapi.common.utils.ReflectionUtil.scheduleLog(ReflectionUtil.java:172)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.shaded.karmapi.common.JarInjector.inject(JarInjector.java:205)
[08:35:44] [Server thread/WARN]: 	at ml.karmaconfigs.playerbth.Main.onEnable(Main.java:35)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[08:35:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[08:35:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[08:35:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[08:35:44] [Server thread/INFO]: Couldn't inject dependency JodaTimeV21010.jar into 2.2.4
[08:35:44] [Server thread/INFO]: [ SERVER ] GRAVE: Failed to inject JodaTime dependency
[08:35:44] [Server thread/INFO]: [PlayerBTH] Disabling PlayerBTH v2.2.4
[08:35:44] [Server thread/INFO]: -------------------
[08:35:44] [Server thread/INFO]:  
[08:35:44] [Server thread/INFO]: Stopping [ GSA ] PlayerBTH
[08:35:45] [Server thread/INFO]:  
```

**Comment by CloudeLecaw** [comment]
seems to be fixed in 2.2.5 :)
